apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    version: v0.1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      version: v0.1.0
  template:
    metadata:
      labels:
        app: api
        version: v0.1.0
    spec:
      containers:
        - name: api
          image: api:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
