apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api-gw
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    # Allows ingress trafic http on port 80 from any host
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api
spec:
  hosts:
    - "*"
  gateways:
    - api-gw
  http:
    # requests with the matching headers will be routed to stable
    - name: http-jc
      match:
        - headers:
            user:
              exact: juancarlo
          ignoreUriCase: true
      route:
        - destination:
            host: api-svc-stable
    # all other requests will fall here
    - name: http-default
      route:
        # start with all traffic going to stable
        # rollouts will update this values for us later on
        - destination:
            host: api-svc-stable
          weight: 100
        - destination:
            host: api-svc-canary
          weight: 0
