apiVersion: v1
kind: Service
metadata:
  name: api-svc-stable
  labels:
    app: api
spec:
  # target a port
  ports:
    - name: http-api
      port: 5000
      protocol: TCP
      targetPort: 5000
  # select pods with this labels
  selector:
    app: api
  type: LoadBalancer
---
# Canary is a copy of stable, it will be updated by rollouts to point to canary version
apiVersion: v1
kind: Service
metadata:
  name: api-svc-canary
  labels:
    app: api
spec:
  ports:
    - name: http-api
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: api
  type: LoadBalancer
