---
apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  namespace: train
spec:
  template:
    spec:
      containers:
        - image: gcr.io/k8s-tech-meeting/docker-repo/train:v1
          imagePullPolicy: IfNotPresent
          name: training1
          command: ["python", "train.py", "-e", "1", "-b", "1024", "-w", "2"]
          volumeMounts:
            - name: cachevol
              mountPath: /root/.cache/
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: CACHE_PATH
              value: /root/.cache/
          resources:
            limits:
              nvidia.com/gpu: "1"
      restartPolicy: Never
      volumes:
        - name: cachevol
          persistentVolumeClaim:
            claimName: cachevol-claim
        - name: dshm
          emptyDir:
            medium: Memory
  backoffLimit: 1
