kind: Namespace
apiVersion: v1
metadata:
  name: train
  labels:
    name: train
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cachevol
  namespace: train
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    # if you're using minikube with driver=docker, you need to access the
    # node (minikube ssh) and create a folder there.
    # If using driver=None this should point to an existing folder on your workstation
    # TODO: remove reference to my home, couldn't make it work
    path: /home/javiber/workspace/k8s-demo/train/.cache
  persistentVolumeReclaimPolicy: Retain # don't delete the volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cachevol-claim
  namespace: train
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
